# Generated by Django 5.1.7 on 2025-03-14 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Huerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plantacion', models.CharField(choices=[('vegetal', 'Vegetal'), ('cereal', 'Cereal')], max_length=10)),
                ('cultivo', models.CharField(choices=[('tomate', 'Tomate'), ('lechuga', 'Lechuga'), ('zanahoria', 'Zanahoria'), ('pimiento', 'Pimiento'), ('cebolla', 'Cebolla'), ('papa', 'Papa'), ('trigo', 'Trigo'), ('maiz', 'Maíz'), ('avena', 'Avena'), ('cebada', 'Cebada'), ('centeno', 'Centeno')], help_text='Seleccione el tipo de cultivo según la plantación', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estacion_siembra', models.CharField(choices=[('primavera', 'Primavera'), ('verano', 'Verano'), ('otoño', 'Otoño'), ('invierno', 'Invierno')], max_length=10)),
                ('estacion_cosecha', models.CharField(choices=[('primavera', 'Primavera'), ('verano', 'Verano'), ('otoño', 'Otoño'), ('invierno', 'Invierno')], max_length=10)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
