# Generated by Django 4.2 on 2025-03-14 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='huerta',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen de la huerta', null=True, upload_to='huertas/'),
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_plantacion', models.DateField()),
                ('fecha_cosecha_estimada', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('huerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='huertas.huerta')),
            ],
        ),
    ]
